### ISSUE TITLE
Telethon can't authenticate with Telegram due to Flask interrupts

### ISSUE THREAD

**Issue by mont77** [nietowl/TeleHuntX#1]
Hey, I tried this app and it runs fine, but when searching the CLI window will display:

'Please enter your phone (or bot token):'

When I enter it, I expect to have to add a code from Telegram - but one is never sent, and the prompt to enter a token never appears, it just tries to POST a request and ignore it.

How can this be fixed?

Thanks

**Comment by PranavDarwai** [comment]
Thanks For Writing 
The easy one enable 2FA (two-factor authentication)
If the issue still persists let me know I will update the code and push the fix as soon as I can
